name: Deploy Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'pump-panel-sim/**'
      - '.github/workflows/deploy-pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: pump-panel-sim/package-lock.json
      
      - name: Install dependencies
        run: |
          cd pump-panel-sim
          npm ci
      
      - name: Build
        run: |
          cd pump-panel-sim
          npm run build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'pump-panel-sim'
          command: pages deploy dist --project-name=fire-pump-panel-simulator